services:
  cpcm-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpcm-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
      - ./outputs:/app/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8501/_stcore/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
